#pragma once

#include "esp_tls.h"

// Certificate symbols generated by CMake EMBED_TXTFILES.
// Linker resolves these from the embedded PEM/key files.
extern const uint8_t ca_pem_start[]     asm("_binary_AmazonRootCA1_pem_start");
extern const uint8_t ca_pem_end[]       asm("_binary_AmazonRootCA1_pem_end");
extern const uint8_t client_crt_start[] asm("_binary_client_crt_start");
extern const uint8_t client_crt_end[]   asm("_binary_client_crt_end");
extern const uint8_t client_key_start[] asm("_binary_client_key_start");
extern const uint8_t client_key_end[]   asm("_binary_client_key_end");

// Create an esp_tls_cfg_t configured for mTLS with embedded certs.
esp_tls_cfg_t tls_create_config(void);
