"""Integration tests for the Supervictor API.

Two tiers:
  local  — HTTP against sam local start-api (no mTLS enforcement).
             Run via: ./scripts/run_integration_tests.sh
  remote — HTTPS + mTLS against a deployed stack.
             Set API_ENDPOINT env var, then: uv run pytest tests/integration/ -m remote

Pytest markers defined in pyproject.toml:
  local, remote, mtls
"""

import pytest
import requests


@pytest.mark.local
class TestLocalSamIntegration:
    """Tests against sam local (HTTP, no mTLS enforcement).

    Validates API structure, response body, and headers via real HTTP calls.
    Requires SAM_LOCAL_URL to be set (done automatically by run_integration_tests.sh).
    """

    def test_get_hello_returns_200(self, sam_local_url: str) -> None:
        response = requests.get(f"{sam_local_url}/", timeout=10)
        assert response.status_code == 200

    def test_response_body_has_message_key(self, sam_local_url: str) -> None:
        response = requests.get(f"{sam_local_url}/", timeout=10)
        body = response.json()
        assert "message" in body

    def test_response_body_message_is_non_empty_string(self, sam_local_url: str) -> None:
        response = requests.get(f"{sam_local_url}/", timeout=10)
        body = response.json()
        assert isinstance(body["message"], str)
        assert len(body["message"]) > 0

    def test_response_content_type_is_json(self, sam_local_url: str) -> None:
        response = requests.get(f"{sam_local_url}/", timeout=10)
        assert "application/json" in response.headers.get("Content-Type", "")

    def test_no_client_subject_in_response_without_cert(self, sam_local_url: str) -> None:
        """sam local passes no cert context — client_subject must be absent."""
        response = requests.get(f"{sam_local_url}/", timeout=10)
        body = response.json()
        assert "client_subject" not in body

    def test_post_uplink_returns_200(self, sam_local_url: str) -> None:
        payload = {"id": "1234567890", "current": 100}
        response = requests.post(f"{sam_local_url}/", json=payload, timeout=10)
        assert response.status_code == 200

    def test_post_uplink_echoes_device_id(self, sam_local_url: str) -> None:
        payload = {"id": "1234567890", "current": 100}
        response = requests.post(f"{sam_local_url}/", json=payload, timeout=10)
        body = response.json()
        assert body["device_id"] == "1234567890"

    def test_post_uplink_missing_body_returns_400(self, sam_local_url: str) -> None:
        response = requests.post(f"{sam_local_url}/", timeout=10)
        assert response.status_code == 400


@pytest.mark.remote
@pytest.mark.mtls
class TestMtlsDeployedIntegration:
    """Tests against the deployed HTTPS endpoint with mTLS.

    Requires:
      API_ENDPOINT  — deployed base URL (e.g. https://supervictor.advin.io)
      test-device cert — generated by: ./scripts/gen_certs.sh device test-device
                         and uploaded CA to s3://supervictor/truststore.pem
    """

    @pytest.mark.skip(reason="403 — test-device cert not in S3 truststore yet")
    def test_valid_client_cert_returns_200(
        self,
        remote_api_url: str,
        test_device_cert: tuple[str, str],
    ) -> None:
        """Full mTLS handshake — API Gateway validates cert against S3 truststore."""
        response = requests.get(
            f"{remote_api_url}/",
            cert=test_device_cert,
            timeout=10,
        )
        assert response.status_code == 200

    @pytest.mark.skip(reason="403 — test-device cert not in S3 truststore yet")
    def test_response_includes_client_subject(
        self,
        remote_api_url: str,
        test_device_cert: tuple[str, str],
    ) -> None:
        """API Gateway injects subjectDN into requestContext; Lambda echoes it."""
        response = requests.get(
            f"{remote_api_url}/",
            cert=test_device_cert,
            timeout=10,
        )
        body = response.json()
        assert "client_subject" in body
        assert "test-device" in body["client_subject"]

    def test_request_without_cert_is_rejected(
        self,
        remote_api_url: str,
    ) -> None:
        """mTLS enforced at API Gateway — request without a cert must be rejected.

        API Gateway can enforce mTLS in two ways:
          - TLS-layer rejection: drops the connection during the handshake,
            resulting in a ConnectionError (no HTTP response at all).
          - HTTP-layer rejection: completes the handshake but returns 403.
        Both are valid; either satisfies the "no cert → rejected" contract.
        """
        try:
            response = requests.get(f"{remote_api_url}/", timeout=10)
            assert response.status_code == 403, (
                f"Expected 403 rejection, got {response.status_code}"
            )
        except requests.exceptions.ConnectionError:
            # TLS handshake was terminated by the server — mTLS is enforced.
            pass
